---
#Main installation actions
#https://clickhouse.com/docs/en/getting-started/#installation

- name: Uninstall by YUM | Ensure clickhouse package uninstalled
  ansible.builtin.dnf:
    name: "{{ clickhouse_package }}"
    state: absent
    autoremove: true
  become: true

- name: Uninstall by YUM | Ensure clickhouse repo uninstalled
  ansible.builtin.yum_repository:
    name: clickhouse
    file: clickhouse
    state: absent
  become: true
